insert into client_information (client_name, org_name, telephone, address, status) values ('Chuck Funk', 'Devpoint', '9876543210', '2 Warrior Avenue', 'Active');
insert into client_information (client_name, org_name, telephone, address, status) values ('Karin Koepp', 'Jayo', '9876543210', '943 Mariners Cove Road', 'Active');
insert into client_information (client_name, org_name, telephone, address, status) values ('Alexis Kautzer', 'Zoombox', '9876543210', '0 Maple Wood Avenue', 'Active');
insert into client_information (client_name, org_name, telephone, address, status) values ('Bettye Jacobson', 'Eare', '9876543210', '15765 Bowman Trail', 'Active');
insert into client_information (client_name, org_name, telephone, address, status) values ('Ramiro Ratke', 'Babbleset', '9876543210', '2 Reindahl Court', 'Active');
insert into client_information (client_name, org_name, telephone, address, status) values ('Towanda VonRueden', 'Buzzdog', '9876543210', '2 8th Circle', 'Active');
insert into client_information (client_name, org_name, telephone, address, status) values ('Kim O''Connell', 'Linktype', '9876543210', '5 Leroy Hill', 'Active');
insert into client_information (client_name, org_name, telephone, address, status) values ('Isaiah Eichmann', 'Skynoodle', '9876543210', '8546 Columbus Plaza', 'Active');
insert into client_information (client_name, org_name, telephone, address, status) values ('Mary Feest', 'Innotype', '9876543210', '59 Katie Drive', 'Active');
insert into client_information (client_name, org_name, telephone, address, status) values ('Christopher Mann', 'Babblestorm', '9876543210', '5 Stang Lane', 'Active');
