insert into employee_information (username, password, name, telephone, email, role) values ('bmosedall0', '1234', 'Brendon Kirlin', '+54 890 5027191', 'mreyson0@nydailynews.com', 'Employee');
insert into employee_information (username, password, name, telephone, email, role) values ('aninnotti1', '1234', 'Shanna Muller', '+74 230 1093271', 'whouldin1@homestead.com', 'Employee');
insert into employee_information (username, password, name, telephone, email, role) values ('ggoodchild2', '1234', 'Tuan Dickens', '+37 664 6567894', 'pmccritichie2@tuttocitta.it', 'Employee');
insert into employee_information (username, password, name, telephone, email, role) values ('tlauritzen3', '1234', 'Cristine Orn', '+70 444 6279071', 'hplummer3@furl.net', 'Employee');
insert into employee_information (username, password, name, telephone, email, role) values ('ttruesdale4', '1234', 'Terrance Rolfson', '+40 466 9903413', 'obazoge4@reference.com', 'Employee');
insert into employee_information (username, password, name, telephone, email, role) values ('awenger5', '1234', 'Blake McKenzie', '+67 183 1262562', 'bkohter5@1688.com', 'Employee');
insert into employee_information (username, password, name, telephone, email, role) values ('bmiddleditch6', '1234', 'Sunshine Swift', '+29 247 1251157', 'jedmans6@unesco.org', 'Employee');
insert into employee_information (username, password, name, telephone, email, role) values ('mashwin7', '1234', 'Shamika Herman', '+68 547 1741437', 'phuniwall7@squarespace.com', 'Employee');
insert into employee_information (username, password, name, telephone, email, role) values ('celgram8', '1234', 'Hiedi Eichmann', '+45 698 7227665', 'emcmearty8@t-online.de', 'Employee');
insert into employee_information (username, password, name, telephone, email, role) values ('ldivine9', '1234', 'Elida Carroll', '+18 395 1405169', 'gogrowgane9@tmall.com', 'Employee');
CREATE TABLE aninnotti1(Date date,project varchar(100),task varchar(100),hour int,description varchar(100));
CREATE TABLE bmosedall0(Date date,project varchar(100),task varchar(100),hour int,description varchar(100));
CREATE TABLE ggoodchild2(Date date,project varchar(100),task varchar(100),hour int,description varchar(100));
CREATE TABLE tlauritzen3(Date date,project varchar(100),task varchar(100),hour int,description varchar(100));
CREATE TABLE ttruesdale4(Date date,project varchar(100),task varchar(100),hour int,description varchar(100));
CREATE TABLE awenger5(Date date,project varchar(100),task varchar(100),hour int,description varchar(100));
CREATE TABLE bmiddleditch6(Date date,project varchar(100),task varchar(100),hour int,description varchar(100));
CREATE TABLE mashwin7(Date date,project varchar(100),task varchar(100),hour int,description varchar(100));
CREATE TABLE celgram8(Date date,project varchar(100),task varchar(100),hour int,description varchar(100));
CREATE TABLE ldivine9(Date date,project varchar(100),task varchar(100),hour int,description varchar(100));